### PR TITLE
Add support for nerdctl ps --all.

### PR DESCRIPTION
**Pull request by shishir-a412ed**
Signed-off-by: Shishir Mahajan <smahajan@roblox.com>

### CODE REVIEW

**Comment by shishir-a412ed** [comment]
ping @AkihiroSuda

```
root@vagrant:~/go/src/nomad-driver-containerd# nerdctl ps --help
NAME:
   nerdctl ps - List containers

USAGE:
   nerdctl ps [command options] [arguments...]

OPTIONS:
   --all, -a   Show all containers (default shows just running) (default: false)
   --no-trunc  Don't truncate output (default: false)
   --help, -h  show help (default: false)
```

```
root@vagrant:~/go/src/nomad-driver-containerd# nerdctl ps
CONTAINER ID    IMAGE                             COMMAND                   CREATED           STATUS     PORTS    NAMES
c596fdd3_hun    docker.io/library/redis:alpine    "docker-entrypoint.s…"    33 minutes ago    Running
root@vagrant:~/go/src/nomad-driver-containerd# nerdctl ps --all
CONTAINER ID    IMAGE                              COMMAND                   CREATED           STATUS     PORTS    NAMES
0f402be30749    docker.io/library/alpine:latest    "/bin/sh"                 25 minutes ago    Created
c596fdd3_hun    docker.io/library/redis:alpine     "docker-entrypoint.s…"    33 minutes ago    Running
```

**Comment by AkihiroSuda** [comment]
Thanks, could you squash commits?

**Comment by shishir-a412ed** [comment]
@AkihiroSuda Done ✅

**Review by AkihiroSuda — APPROVED** [review]
Thanks

**Pull request merged**
