### PR TITLE
add `nerdctl network create`

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Note:
- To isolate CNI bridge, CNI isolation plugin needs to be installed: https://github.com/AkihiroSuda/cni-isolation
- No support for looking up container IPs by their names yet

### CODE REVIEW

**Comment by rossbachp** [comment]
Seems for me a useful feature. Please, use newer versions of containerd v1.4.3 and cni v0.9.0!

**Comment by rossbachp** [comment]
Hello,

Why a can attach to the networks? 

Check with containerd 1.3.8 and 1.4.3 with cni 0.9.0.

Why the created networks doesn't created?
check with `ip a s`

```
ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:56:4a:18:02:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.64.9/24 brd 192.168.64.255 scope global dynamic enp0s2
       valid_lft 84769sec preferred_lft 84769sec
    inet6 fe80::56:4aff:fe18:22d/64 scope link 
       valid_lft forever preferred_lft forever
ubuntu@container:~/nerdctl$ sudo mkdir -p /etc/cni/net.d 
ubuntu@container:~/nerdctl$ sudo /bin/bash
root@container:/home/ubuntu/nerdctl# nerdctl network ls
NAME       KIND
nerdctl    nerdctl (builtin)
root@container:/home/ubuntu/nerdctl# nerdctl run -ti busybox ip a s
docker.io/library/busybox:latest:                                                 resolved       |++++++++++++++++++++++++++++++++++++++| 
index-sha256:49dae530fd5fee674a6b0d3da89a380fc93746095e7eca0f1b70188a95fd5d71:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:99243e861067446c9aed305b5690cccb88658d23af3fde338398f27386ded1be: done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:a77dce18d0ecb0c1f368e336528ab8054567a9055269c07c0169cba15aec0291:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:d60bca25ef07e48961711a71bd92e771efdd574b87f3c254f06c0499404c56a1:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 3.1 s                                                                    total:  752.6  (242.7 KiB/s)                                     
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
root@container:/home/ubuntu/nerdctl# 
nerdctl network create --subnet 10.5.0.0/16 mynet
WARN[0000] CNI support is WIP. No isolation across different networks. 
root@container:/home/ubuntu/nerdctl# nerdctl run -ti --network mynet busybox ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
```

**Comment by AkihiroSuda** [comment]
Does cnitool work, or print some meaningful error? https://www.cni.dev/docs/cnitool/

**Comment by rossbachp** [comment]
Which meaningful command you want?

```
cnitool check mynet
cnitool: Add, check, or remove network interfaces from a network namespace
  cnitool add   <net> <netns>
  cnitool check <net> <netns>
  cnitool del   <net> <netns>
root@container:/home/ubuntu/cnitool# nerdctl run -ti busybox ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
root@container:/home/ubuntu/cnitool# nerdctl network ls
NAME       KIND
nerdctl    nerdctl (builtin)
mynet      nerdctl
```

I use a multpass ubuntu 20.04.1 LTS

```
uname -a
Linux container 5.4.0-54-generic #60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@container:/home/ubuntu/cnitool# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by rossbachp** [comment]
After I create the network it doesn't exists!

The nerdctl network inspect needed a installation of `netctl`
 
```
nerdctl network create --subnet 10.6.0.0/16 mynet2 
WARN[0000] CNI support is WIP. No isolation across different networks. 
root@container:/home/ubuntu/cnitool# cat /etc/lsb-release ^C
root@container:/home/ubuntu/cnitool# ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 02:56:4a:18:02:2d brd ff:ff:ff:ff:ff:ff
    inet 192.168.64.9/24 brd 192.168.64.255 scope global dynamic enp0s2
       valid_lft 80257sec preferred_lft 80257sec
    inet6 fe80::56:4aff:fe18:22d/64 scope link 
       valid_lft forever preferred_lft forever
root@container:/home/ubuntu/cnitool# nerdctl network inspect mynet2
[
    {
        "CNI": {
            "cniVersion": "0.4.0",
            "name": "mynet2",
            "nerdctl": true,
            "plugins": [
                {
                    "type": "bridge",
                    "bridge": "cni-nerdctl-mynet2",
                    "isGateway": true,
                    "ipMasq": true,
                    "hairpinMode": true,
                    "ipam": {
                        "type": "host-local",
                        "routes": [
                            {
                                "dst": "0.0.0.0/0"
                            }
                        ],
                        "ranges": [
                            [
                                {
                                    "subnet": "10.6.0.0/16",
                                    "gateway": "10.6.0.1"
                                }
                            ]
                        ]
                    }
                },
                {
                    "type": "portmap",
                    "capabilities": {
                        "portMappings": true
                    }
                },
                {
                    "type": "firewall"
                },
                {
                    "type": "tuning"
                }
            ]
        },
        "Nerdctl": true,
        "File": "/etc/cni/net.d/nerdctl-mynet2.conflist"
    }
]
```

**Comment by rossbachp** [comment]
OK!

I tryout this:

```
ip netns add testing
export CNI_PATH=/opt/cni/bin
cnitool add mynet2 /var/run/netns/testing
failed to create bridge "cni-nerdctl-mynet2": could not add "cni-nerdctl-mynet2": numerical result out of range
```

**Comment by AkihiroSuda** [comment]
Fixed the network name length issue, thanks

**Pull request merged**
